import type { DealRecord, DomainRecord, LeadRecord } from '@/types/domain'

export const demoDomains: DomainRecord[] = [
  {
    id: 'amsterdamdakdekker-nl',
    domainName: 'amsterdamdakdekker.nl',
    tld: '.nl',
    language: 'NL',
    category: 'Home services',
    status: 'listed',
    sellMode: 'portfolio_redirect',
    currentRegistrar: 'xel',
    acquisitionCost: 95,
    annualRenewalCost: 12,
    quickSalePrice: 850,
    targetPrice: 1900,
    aspirationalPrice: 3200,
    migrationCandidate: true,
    targetRegistrar: 'openprovider',
    notes: 'Strong geo + service pairing for local roofing businesses.',
  },
  {
    id: 'greenbatteryhub-com',
    domainName: 'greenbatteryhub.com',
    tld: '.com',
    language: 'EN',
    category: 'Energy',
    status: 'listed',
    sellMode: 'portfolio_redirect',
    currentRegistrar: 'xel',
    acquisitionCost: 210,
    annualRenewalCost: 14,
    quickSalePrice: 1400,
    targetPrice: 3900,
    aspirationalPrice: 6800,
    migrationCandidate: false,
    notes: 'Commercial phrase with broad energy storage applicability.',
  },
  {
    id: 'rotterdamseo-nl',
    domainName: 'rotterdamseo.nl',
    tld: '.nl',
    language: 'NL',
    category: 'Marketing',
    status: 'outbound_research',
    sellMode: 'portfolio_redirect',
    currentRegistrar: 'xel',
    acquisitionCost: 45,
    annualRenewalCost: 12,
    quickSalePrice: 600,
    targetPrice: 1450,
    aspirationalPrice: 2600,
    migrationCandidate: true,
    targetRegistrar: 'dynadot',
    notes: 'Good local SEO agency positioning with easy buyer discovery.',
  },
  {
    id: 'urbanlease-ai',
    domainName: 'urbanlease.ai',
    tld: '.ai',
    language: 'EN',
    category: 'SaaS',
    status: 'inbound_only',
    sellMode: 'portfolio_redirect',
    currentRegistrar: 'xel',
    acquisitionCost: 180,
    annualRenewalCost: 72,
    quickSalePrice: 1200,
    targetPrice: 3400,
    aspirationalPrice: 5400,
    migrationCandidate: false,
    notes: 'Brandable vertical AI domain with moderate holding cost.',
  },
]

export const demoLeads: LeadRecord[] = [
  {
    id: 'lead-1',
    domainId: 'amsterdamdakdekker-nl',
    companyName: 'DakPro Amsterdam',
    website: 'https://dakpro-amsterdam.example',
    contactName: 'Milan de Vries',
    contactEmail: 'milan@dakpro-amsterdam.example',
    buyerFitReason: 'Exact service geography match with existing local brand.',
    priorityScore: 89,
    doNotContact: false,
    country: 'NL',
    source: 'manual',
  },
  {
    id: 'lead-2',
    domainId: 'rotterdamseo-nl',
    companyName: 'Haven Digital',
    website: 'https://havendigital.example',
    contactName: 'Sanne Visser',
    contactEmail: 'sanne@havendigital.example',
    buyerFitReason: 'Owns several Rotterdam-focused agency landing pages.',
    priorityScore: 81,
    doNotContact: false,
    country: 'NL',
    source: 'csv-import',
  },
]

export const demoDeals: DealRecord[] = [
  {
    id: 'deal-1',
    domainId: 'greenbatteryhub-com',
    leadId: 'lead-2',
    closingMethod: 'escrow_com',
    status: 'awaiting_payment',
    agreedPrice: 3200,
    paymentSecured: false,
    buyerApprovalState: 'pending',
  },
  {
    id: 'deal-2',
    domainId: 'amsterdamdakdekker-nl',
    leadId: 'lead-1',
    closingMethod: 'escrow_com',
    status: 'seller_transfer_required',
    agreedPrice: 1500,
    paymentSecured: true,
    buyerApprovalState: 'approved',
  },
]
